# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

fish_config theme choose "Catppuccin Macchiato"

set -gx fish_key_bindings fish_user_key_bindings

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases
    alias cookie 'cookiecutter my --directory'
    alias eza 'eza --git'
    alias je 'jupyter execute --inplace'
    alias jn 'jupyter notebook'
    alias jt 'jupytext --update --to notebook'
    alias jpg2webm 'ffmpeg -r 30 -i %d.jpg output.webmm'
    alias l 'eza -l -g --icons'
    alias la ll
    alias ll 'l -a'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'
    alias s 'kitten ssh'

    # Interactive shell initialisation
    fzf --fish | source

    set -gx fish_key_bindings fish_user_key_bindings

    zoxide init fish | source

    if test "$TERM" != dumb
        starship init fish | source

    end

    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION no-rc
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/doeringc/.local/share/fish/home-manager/generated_completions" $post
    end

    atuin init fish | source

    direnv hook fish | source

end
