# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/y58snd6ysxnbp4d6lr4h281ddkr0q3fy-hm-session-vars.fish

fish_config theme choose "Catppuccin Macchiato"

set -gx fish_key_bindings fish_user_key_bindings

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations

    # Aliases
    alias cookie 'cookiecutter my --directory'
    alias eza 'eza --git'
    alias je 'jupyter execute'
    alias jn 'jupyter notebook'
    alias jpg2webm 'ffmpeg -r 30 -i %d.jpg output.webmm'
    alias jt 'jupytext --update --to notebook'
    alias l 'eza -l -g --icons'
    alias la ll
    alias ll 'l -a'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'

    # Interactive shell initialisation
    /nix/store/lc3zmvfh5cyzdgijm8f5sjgd0q3hl9pk-fzf-0.67.0/bin/fzf --fish | source

    set -gx fish_key_bindings fish_user_key_bindings

    /nix/store/5g10iizw7yacs5kr8s7l3v6hirjw9i15-zoxide-0.9.8/bin/zoxide init fish | source

    if test "$TERM" != dumb
        /nix/store/lfw8yb2nhj04fcfb7lc5zl6mh6m6n5l1-starship-1.24.1/bin/starship init fish | source

    end

    if set -q KITTY_INSTALLATION_DIR
        set --global KITTY_SHELL_INTEGRATION no-rc
        source "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish"
        set --prepend fish_complete_path "$KITTY_INSTALLATION_DIR/shell-integration/fish/vendor_completions.d"
    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/doeringc/.local/share/fish/home-manager/generated_completions" $post
    end

    /nix/store/pgpzq3waplzadryhxigjk2l1s33a2yj9-atuin-18.10.0/bin/atuin init fish | source

    /nix/store/wpj4la1jgf0p8aimfzx49gfr3228vk8f-direnv-2.37.1/bin/direnv hook fish | source

end
